// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFJD3D0mapRatOpLF3RmzZFEP_HG5VwpU',
    appId: '1:609481354625:web:79f78368d1bf19b0c30c80',
    messagingSenderId: '609481354625',
    projectId: 'book-app-ff535',
    authDomain: 'book-app-ff535.firebaseapp.com',
    storageBucket: 'book-app-ff535.firebasestorage.app',
    measurementId: 'G-RVKTXFJTMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHMFsTs3GMN1FQV9oNEbComInnFHEB1Zs',
    appId: '1:609481354625:android:f3a6064597eab24fc30c80',
    messagingSenderId: '609481354625',
    projectId: 'book-app-ff535',
    storageBucket: 'book-app-ff535.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxn34sjc_15x0EiryyomELDUtlpTxPdrE',
    appId: '1:609481354625:ios:fb9e267afc5d5343c30c80',
    messagingSenderId: '609481354625',
    projectId: 'book-app-ff535',
    storageBucket: 'book-app-ff535.firebasestorage.app',
    iosBundleId: 'com.example.bookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxn34sjc_15x0EiryyomELDUtlpTxPdrE',
    appId: '1:609481354625:ios:fb9e267afc5d5343c30c80',
    messagingSenderId: '609481354625',
    projectId: 'book-app-ff535',
    storageBucket: 'book-app-ff535.firebasestorage.app',
    iosBundleId: 'com.example.bookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFJD3D0mapRatOpLF3RmzZFEP_HG5VwpU',
    appId: '1:609481354625:web:71a5184b9390cd76c30c80',
    messagingSenderId: '609481354625',
    projectId: 'book-app-ff535',
    authDomain: 'book-app-ff535.firebaseapp.com',
    storageBucket: 'book-app-ff535.firebasestorage.app',
    measurementId: 'G-1D5N9TVQQC',
  );
}
